version: '3.8'

services:
  sep-scraper:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sep-scraper
    ports:
      - "8010:8010"
    environment:
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8010/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s 